# @package hydra
# job:
#   config:
#     # configuration for the ${hydra.job.override_dirname} runtime variable
#     override_dirname:
#       exclude_keys: [name, hydra.launcher, launcher, hydra.launcher.array_parallelism, run] # , dataset, model] #, experiment_name, seed, pretrained_checkpoint, epochs, finetune_epochs, val_check_interval, limit_train_batches]

run:
  # Output directory for normal runs
  dir: ${logdir}/${name}/${now}
  # dir: ${paths.logdir}/${paths.rundir}/${seed}
  # dir: ${paths.logdir}/${experiment_name}_${hydra.job.override_dirname}/${seed}
  # dir: ${paths.logdir}/${dataset.name}/${model.name}/${experiment_name}/${hydra.job.override_dirname}/${seed}
  # dir: ${paths.experiments}/${name}/${hydra.job.override_dirname}/${run}
sweep:
#   # Output directory for sweep runs
  dir: ${logdir}/${name}/${hydra.job.override_dirname}/${now}
  # dir: ${paths.logdir}/${experiment_name}_${hydra.job.override_dirname}
  # dir: ${paths.logdir}/${dataset.name}/${model.name}/${experiment_name}/${hydra.job.override_dirname}
  # dir: ${paths.experiments}/${name}/${hydra.job.override_dirname}
  subdir: ${seed}

job_logging:
  formatters:
    simple:
      format: '[%(levelname)s] - %(message)s'
  handlers:
    file:
      filename: run.log
  root:
    handlers: [console, file]