defaults:
  # GENERAL #
  - _self_

  - server: local
  - experiment: s2_toy

  - logger: csv

  - optim: adam
  - scheduler: rcosine
  - beta_schedule: linear
  
  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

eval_batch_size: ${batch_size}
now: ${now:%Y-%m-%d}/${now:%H-%M-%S}

resume: false
mode: all
seed: 0
PROJECT_NAME: score-sde
work_dir: ${hydra:runtime.cwd}

# path to folder with data
data_dir: ${work_dir}/data/
ckpt_dir: ckpt
logs_dir: logs

logdir: ${work_dir}/results
# rundir: ${dataset.name}/${model.name}

# perform actions in the val loop during training
train_val: true
train_plot: true

# perform certain metrics in test mode
test_val: true
test_test: true
test_plot: true