# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 840
cpus_per_task: 1
tasks_per_node: 1
mem_gb: 10
# name: ${experiment_name}_${dataset.name}_${model.name}
partition: ziz-gpu
max_num_timeout: 0
array_parallelism: 3
additional_parameters: {
  "wckey": "bigbayes_project",
  "gres": "gpu:GeForce_GTX_1080:1",
  # "nodelist": "zizgpu04.cpu.stats.ox.ac.uk",
}